esphome:
  name: garage_controller
  platform: ESP32
  board: featheresp32

wifi:
  ssid: wifi_ssid
  password: wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "garage_controller"

ota:
  password: "garage_controller"

sensor:
  - platform: dht
    pin: 21
    model: DHT22
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 60s

i2c:
  sda: SDA
  scl: SCL
  scan: True

mcp23017:
  - id: "hub_a"
    address: 0x27

# 0.0 = 0% = CLOSED
# 1.0 = 100% = OPEN
binary_sensor:
  - platform: status
    name: "Garage Controller Status"
  # Garage Bay 1
  - platform: gpio
    name: "Garage Bay 1 Opened"
    pin:
      mcp23017: hub_a
      number: 8
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_1
            state: OPEN
            current_operation: IDLE
    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_1
            current_operation: CLOSING

  - platform: gpio
    name: "Garage Bay 1 Closed"
    pin:
      mcp23017: hub_a
      number: 9
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_1
            state: CLOSED

    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_1
            current_operation: OPENING

  # Garage Bay 2
  - platform: gpio
    name: "Garage Bay 2 Opened"
    pin:
      mcp23017: hub_a
      number: 10
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_2
            state: OPEN
    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_2
            current_operation: CLOSING

  - platform: gpio
    name: "Garage Bay 2 Closed"
    pin:
      mcp23017: hub_a
      number: 11
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_2
            state: CLOSED
    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_2
            current_operation: OPENING

  # Garage Bay 3
  - platform: gpio
    name: "Garage Bay 3 Opened"
    pin:
      mcp23017: hub_a
      number: 12
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_3
            state: OPEN
    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_3
            current_operation: CLOSING

  - platform: gpio
    name: "Garage Bay 3 Closed"
    pin:
      mcp23017: hub_a
      number: 13
      mode: INPUT
    on_press:
      then:
        - cover.template.publish:
            id: garage_cover_3
            state: CLOSED
    on_release:
      then:
        - cover.template.publish:
            id: garage_cover_3
            current_operation: OPENING

# Define our relays. Keep them private.
switch:
  - platform: gpio
    pin:
      mcp23017: hub_a
      number: 0
      mode: OUTPUT
    id: relay_1
  - platform: gpio
    pin:
      mcp23017: hub_a
      number: 1
      mode: OUTPUT
    id: relay_2
  - platform: gpio
    pin:
      mcp23017: hub_a
      number: 2
      mode: OUTPUT
    id: relay_3
  - platform: gpio
    pin:
      mcp23017: hub_a
      number: 3
      mode: OUTPUT
    id: relay_4

cover:
  - platform: template
    name: "Garage Door 1"
    device_class: garage
    id: garage_cover_1
    open_action:
      - switch.turn_on: relay_1
      - delay: 500ms
      - switch.turn_off: relay_1
    close_action:
      - switch.turn_on: relay_1
      - delay: 500ms
      - switch.turn_off: relay_1
    stop_action:
      - switch.turn_on: relay_1
      - delay: 500ms
      - switch.turn_off: relay_1
  - platform: template
    name: "Garage Door 2"
    device_class: garage
    id: garage_cover_2
    open_action:
      - switch.turn_on: relay_2
      - delay: 500ms
      - switch.turn_off: relay_2
    close_action:
      - switch.turn_on: relay_2
      - delay: 500ms
      - switch.turn_off: relay_2
    stop_action:
      - switch.turn_on: relay_2
      - delay: 500ms
      - switch.turn_off: relay_2
  - platform: template
    name: "Garage Door 3"
    device_class: garage
    id: garage_cover_3
    open_action:
      - switch.turn_on: relay_3
      - delay: 500ms
      - switch.turn_off: relay_3
    close_action:
      - switch.turn_on: relay_3
      - delay: 500ms
      - switch.turn_off: relay_3
    stop_action:
      - switch.turn_on: relay_3
      - delay: 500ms
      - switch.turn_off: relay_3
